### ISSUE TITLE
Apply new style when tab menus are switched

### ISSUE THREAD

**Issue by irrationnelle** [daangn/stackflow#152]
AS-IS:

https://user-images.githubusercontent.com/10165823/160276839-bbda3def-6caf-4d15-bc7e-b2508210196b.mov

TO-BE:

It should be prepared a proper style to fit switched tab menus.

**Comment by tonyfromundefined** [comment]
`@karrotframe/tabs`는 이제 Stackflow에서 지원하지 않습니다.
