### ISSUE TITLE
useFlow animate 구현여부

### ISSUE THREAD

**Issue by devxian96** [daangn/stackflow#190]
https://stackflow.so/guided-tour/navigating
문서를 읽어보고 있는데 animate 옵션이 구현이 안되어 있는것 같아 질문드립니다.

라이브러리를 살펴보니 매개변수로 animate를 받고 있지만 별도로 처리하는 코드는 보이지 않았습니다.
구현 예정임으로 미리 문서에 작성해 두신건지, 아니면 잘못 이해한 건지 확인 부탁드립니다.

`replace('Main', { title: 'Main' }, { animate: false })`
`push('Main', { title: 'Main' }, { animate: false })`

**Comment by irrationnelle** [comment]
안녕하세요. 이슈 등록 감사드려요!

animate 매개변수는 7월 11일에 구현하여 업데이트 및 배포 예정이에요.

**Comment by devxian96** [comment]
좋은 코드와 일정 공유 감사합니다!

**Comment by irrationnelle** [comment]
@devxian96 

안녕하세요. 이슈로 남겨주셨던 animate 옵션 관련 변경사항(https://github.com/daangn/stackflow/pull/189) 을 merge 하고 배포했어요.

아래 업데이트 한 패키지 버전을 사용하시면 이제 `animate` 옵션을 다루실 수 있어요.

```
@stackflow/core@0.4.0
@stackflow/basic-ui@0.5.0
@stackflow/plugin-history-sync@0.6.0
@stackflow/plugin-renderer-basic@0.5.0
@stackflow/react@0.5.0
```

다시 한 번 피드백 감사드려요!
