### ISSUE TITLE
Activity parameters throws error when reserved words in react props used (ex: `ref`)

### ISSUE THREAD

**Issue by Ha-Young** [daangn/stackflow#206]
query string에 ref를 주면 애러가 발생하네요
activity component에서 query string을 props로 받으면서 문제가 발생하는 것 같아요.
e.g) http://localhost:3000/#/?ref=not_working

`Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref`

`ref` query는 기존에 쓰이고있던거라 해결이 필요해보여요

**Comment by tonyfromundefined** [comment]
ㅘㅜ....

**Comment by Ha-Young** [comment]
ReactComponent 타입에서 ref props를 못받는거라면 다른 커스텀 컴포넌트 타입이나 래핑한 타입을 만들어보면 어떨까요?

**Comment by ginger-kang** [comment]
@Ha-Young 네넵~ 오전에 스크럼때는 넘어오는 props들을 params={activity.params}같이 한번 더 감싸서 제공하는 것도 러프하게 얘기가 나왔어요

**Comment by tonyfromundefined** [comment]
> 아하 아니면 query로 받는것은 아예 query property로 조정해도 될 것 같아요

TMI: 스택플로우는 기본적으로 URL에 대한 관심사를 격리해서 관리하고 있어요 ㅎㅎ 따라서 코드 내에서 path, query 등등의 키워드를 쓰는걸 권장하지 않고 있고, 프레임워크 단에서 제공하지 않을 예정이에요.
