### ISSUE TITLE
When npm version 1.0?

### ISSUE THREAD

**Issue by gron1gh1** [daangn/stackflow#230]
안녕하세요 ! 실제 프로덕트에 적용해도 안전성이 있을  npm 버전 1.0.0 계획이 있나요 ??

**Comment by tonyfromundefined** [comment]
이 라이브러리를 프로덕트에서 실제로 사용하고 있는 팀이 많이 있습니다. 자잘자잘한 수정사항은 지속적으로 발생할것 같은데, 마이그레이션 비용이 드는 과도하게 파괴적인 변화는 앞으로 없을 예정입니다.

하지만 아직까지 인터페이스가 바뀔 수 있는 여지가 조금 있어서, 1.0.0으로의 버전 변경은 당분간(2022년 이내)은 계획되지 않았습니다.

**Comment by gron1gh1** [comment]
답변 감사합니다 !!
