### ISSUE TITLE
push시 animation direction설정이 가능할까요?

### ISSUE THREAD

**Issue by nogomin** [daangn/stackflow#236]
push시에 아래에서 위로 컴포넌트가 올라오도록 하고싶은데, 방향설정 부분은 플러그인확장을 통해 구현해야하는건가요?

**Comment by nogomin** [comment]
Appscreen의 theme을 설정하면 되는군요. 잘쓰겠습니다!

**Comment by hmmhmmhm** [comment]
혹시 방향을 아래에서 위 말고, 데모처럼 좌에서 우로도 가능할까요?

**Comment by nogomin** [comment]
basic ui에서 Appscreen컴포넌트를 제공하는데 거기 props에 theme=cupertino로 주면 좌에서 우로 이동합니다 아래에서 위는 android입니다.

**Comment by hmmhmmhm** [comment]
빠른 공유 감사합니다! Next.js 샘플에서  src/pages/_app.tsx 에서
```
const STACKFLOW_BASIC_UI_THEME_SCRIPT = dedent`
  (() => {var c=/iphone|ipad|ipod/i.test(window.navigator.userAgent.toLowerCase()),e=document.documentElement;e.dataset.stackflowBasicUiTheme="cupertino";})()
`;
```
이 부분도 수정을 주니 동작하네요!
