### ISSUE TITLE
명령형 구성 인터페이스

### ISSUE THREAD

**Issue by cometkim** [daangn/stackflow#292]
리스크립트 바인딩 요청을 받았는데 현재의 선언적 구성 인터페이스는 타입스크립트의 타입시스템 표현력에 많이 의존적이여서 다른언어 그대로 활용하기가 어려워요.

한 가지 방법은 DSL 을 만들어서 코드 생성을 하는 건데 일단 거기까지 안가고 런타임 코드 바인딩을 시도해보려고 해요.

타입시스템 표현력에 크게 의존하지 않아도 초기 구성을 할 수 있도록 명령형 인터페이스로 구성하는 방법을 제공해주세요.

예시)

```ts
import { stackflow } from "@stackflow/react";

export const Instance = stackflow({
  transitionDuration: 350,
});

Instance.addPlugin();
Instance.addActivity();
```

**Comment by tonyfromundefined** [comment]
0.19.0으로 릴리즈 되었어요~
