### ISSUE TITLE
window check

### ISSUE THREAD

**Issue by tooooo1** [daangn/stackflow#335]
안녕하세요. 코드를 보며 학습하던 중 궁금한 점이 생겨서 이슈 남겨봅니다!

stackflow 여러 곳에서 `const isServer = typeof window === "undefined";`이나 `const isBrowser = typeof window !== "undefined";`같이 window를 체크하는 부분이 따로따로 있는 것을 발견했어요. 

![image](https://user-images.githubusercontent.com/77133565/215396847-0bdacc4c-0e9d-4f98-bee4-9a61d1e69dea.png)

변수명을 주지않고 `typeof window !== "undefined"`로 바로 체킹하는 곳도 찾을 수 있었는데요.
![image](https://user-images.githubusercontent.com/77133565/215397076-55f631ef-e8ad-4056-a846-f8931ee08e6c.png)

더 많아지기 전에 이들을 하나로 관리하면 더 좋지 않을까?라고 생각해봤습니다.

```ts
export function isServer() {
  return typeof window === 'undefined';
}
```
으로 빼고,

```ts
import { isServer } from './isServer';

export function isBrowser() {
  return !isServer();
}
```
다른 곳에서는 역전 시킨 후 이름을 주며 `window type`을 관리하는 건 어떨까요..? 
많이 부족하지만 조심스럽게 제안해 봅니다..!

아래는 제가 찾은 부분에 대해 경로를 모아봤어요.

- integrations\react\src\stackflow.tsx
- extensions\plugin-basic-ui\src\basicUIPlugin.tsx
- extensions\plugin-history-sync\src\historyState.ts
- extensions\plugin-history-sync\src\historySyncPlugin.tsx

위 4가지 파일에서 7군데가 흩어져 있어요.

**Comment by tonyfromundefined** [comment]
좋습니다! 가능하시다면 PR 부탁드려도 될까요? 직접 커밋 넣으시는게 뿌듯하실 것 같아서요. 힘드시면 저희가 리팩토링 PR 넣을게요. 원하시는 방향을 결정해주세요.

**Comment by tooooo1** [comment]
엇 제가 그래도 될까요..? 하고 싶어요! PR 만들어서 올려볼게요!
