### ISSUE TITLE
[IOS] 기본 뒤로가기 스와이프시 레이아웃 깨짐

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [daangn/stackflow#371]
좋은 라이브러리 제공해주셔서 감사합니다.

https://stackflow-example-nextjs-git-preload-plugin-karrot.vercel.app/

위 데모 페이지에서 `IOS환경`에서 살펴보았는데요, app bar 좌측에 존재하는 화살표 버튼이 아닌, IOS기본 좌측에서 우측으로 **스와이프** 하는 액션을 취하면 레이아웃이 뒤틀리면서 깨지는 현상이 발생합니다.

https://user-images.githubusercontent.com/69495129/225058102-7e3d66f3-ca85-417c-96be-8c304104e114.mp4

아마 Activity를 POP하는 과정에서 꼬이는것 같은데 `Known Issue` 일까요?
https://stackflow.so/ 최상단 데모 버전에서도 같은 이슈가 발생하는것을 보면 `nextjs`이여서 발생한 이슈는 아닌 것 같습니다.

**Comment by tonyfromundefined** [comment]
- Stackflow 는 모바일 웹을 작성하는데 최적화된 Framework는 아닙니다. 대신 모바일 웹뷰 환경이나 하이브리드 앱 환경에 알맞게 쓰일 수 있습니다.
- 가장 이상적으로는 iOS 클라이언트 내의 WKWebView(모바일 웹뷰)에서 Swipe Back Behavior을 Disable 한 채로 Stackflow를 얹어서 사용하는 것이 알맞습니다.

**Comment by ChanhyukPark-Tech** [comment]
두분 빠른 답변 감사해요.

플랫폼별로 다르게 구현해야할수도 있겠네요.

>가장 이상적으로는 iOS 클라이언트 내의 WKWebView(모바일 웹뷰)에서 Swipe Back Behavior을 Disable 한 채로 Stackflow를 얹어서 사용하는 것이 알맞습니다.

이상적인 해결 가이드라인도 제공해주셔서 감사해요.😄

**Comment by daeuk1011** [comment]
안녕하세요!
Stacflow에서 swipe back을 disable 할 수 있는 옵션이 없을까요?
