### ISSUE TITLE
새로고침 시 back 버튼이 날아가는 현상

### ISSUE THREAD

**Issue by daseuls** [daangn/stackflow#403]
안녕하세요. 좋은 라이브러리 만들어주셔서 감사합니다.
현재 리뉴얼하는 프로젝트에 도입하기 전에 테스트 중입니다. 

액티비티 위에서 새로고침을 하게 되면 뒤로가기 버튼이 사라지게 되는데
해결할 수 있는 방법이 있을까요?

유저가 액티비티 화면에서 어떠한 상황때문에 새로고침이 생길경우가 있을 텐데 
리뉴얼하는 프로젝트의 경우 앱에서 동작되기 때문에 뒤로가기 버튼이 필요하기때문입니다..! 😥

https://github.com/daangn/stackflow/assets/71131248/b7c60a25-4416-4fb2-ac2b-1d3353da693d

**Comment by SimYunSup** [comment]
> 새로고침을 하게되면 뒤로가기 버튼이 사라지게 되는데

이 말씀과 영상을 보니 `history-sync-plugin`을 사용중을 가정하고 답변하겠습니다.
이 라이브러리는 내부에서 `windows`가 존재할 경우 `BrowserRouter`를 사용하고 있습니다. 이는 history API 기반으로 되어 있어 새로고침 할 경우 history context를 모두 날리게 됩니다(보안 이슈로 history API에 전 화면의 주소는 가져오지 못합니다).

이에 대응하는 방법은 두가지가 있습니다.

1. `history@4.x.x` 패키지의 `createMemoryHistory`를 통해 localStorage에 저장하여  history context를 저장해 새로고침 시 history context를 복구하는 history 객체를 만든다. `history-sync-plugin`의 옵션에 삽입하면 완료.
2. 커스텀 history를 만든다.

앱 위에서 작동하는 것이라면 새로고침을 방지하는 것 또한 좋은 방법이 될 것 같습니다. 혹여나 무조건 새로고침을 해야하는 상황이라면 위 방법을 검토해보세요 :)
