### ISSUE TITLE
`@stackflow/plugin-history-sync` 에서 앞으로 가기 지원 안 함

### ISSUE THREAD

**Issue by ynifamily3** [daangn/stackflow#419]
https://github.com/daangn/stackflow/assets/13795765/4ce6acdc-af08-4149-92e6-0269ab8be178

뒤로가기 (백버튼) 은 지원을 하나 앞으로 가기를 지원하지 않습니다. 혹시 지원 예정 있을까요?

**Comment by tonyfromundefined** [comment]
엇 원래 지원했었는데, 최근 커밋에 버그가 있는것 같네요. 확인해보겠습니다

**Comment by ynifamily3** [comment]
@tonyfromundefined 감사합니다. 혹시 다음과 같은 영상도 동일한 버그일까요? (브라우저 뒤로가기 지원 안 될 때도 있음)


https://github.com/daangn/stackflow/assets/13795765/e32f7176-9883-4282-8452-186c17e1fdef

**Comment by tonyfromundefined** [comment]
`@stackflow/plugin-history-sync`의 버전을 1.3.9로 다운그레이드 해보시겠어요? 해당 버전은 정상작동합니다

**Comment by orionmiz** [comment]
`@stackflow/plugin-history-sync@1.3.12`에서 수정되었어요~ 이슈 제보 감사드려요
