### ISSUE TITLE
Stackflow Docs v2

### ISSUE THREAD

**Issue by ho991217** [daangn/stackflow#522]
<img src="https://github.com/user-attachments/assets/dc27b204-0c5f-4d96-a6df-e5d11a753a4e" alt="banner" />

---
### Title
- Stackflow
- The Flexible Stack Navigation UI Library
> Shows demo

### Features
- Headless Architecture: Use stack and transition states without pre-built UI, allowing full customization.
- Plugin-Driven Extensibility: Inject custom functionality via plugin interfaces at any lifecycle stage.
- Framework Agnostic: Seamlessly integrate with diverse frontend frameworks due to its decoupled core logic.
- Cross-Platform Rendering: Inject custom render logic to build both mobile web views and desktop apps from a single codebase.
- TypeScript & Server-Side Rendering support ensures scalability and performance.

> Some icons or info graphics might be useful.

---
### Introduction
- What is Stackflow?
- Design and principles
- Architecture
- Decision Log 
> Optional. is good to have

#### Installation
- Installation and Configuration
- Setting up basic UI
#### Activity
- Activity
- Registering a Activity
- Adding initial Activity
- Registering required parameters
#### Exploring
- Stacking new Activity
- Replacing current Activity
- Popping top Activity

#### Step
- Stacking Step
- Replacing Step
- Popping top Step
#### State
- Getting states
- Use Stack states for render
- Use Activity states for render
#### Customization
- Customize UI
#### Make Your Own Plugin
- Writing preset
- Basic interface
- Add render method
- Wrapping Stack
- Wrapping Activity
- Injecting action on init
- Effect hooks
- Determining initial Activity

---
### Configuration
> Configuration in Activity
### Activity
> Fields in Activity
#### `react-ui-core`
---
## Extras
> - Supports Korean and English
> - New logo
> - Bump nextra version to v3 (perhaps to v4)
> - Add OpenGraph image

<img width="16px" height="16px" src="https://github.com/user-attachments/assets/d1cb39e4-8647-4f23-8d8a-4f3ffd2ce18a" alt="logo" /> Stackflow documentation v2

**Comment by tonyfromundefined** [comment]
Thanks for the suggestion! I approve everything

**Comment by XiNiHa** [comment]
Hey, as the one working on https://github.com/daangn/stackflow/pull/473, if you're considering merging it upstream 😂 could you also have adding Solid docs in mind? I'll definitely write the actual docs but I'd appreciate it if the structure of the docs is prepared for it 😋

**Comment by ho991217** [comment]
Hello, @XiNiHa. If you plan to contribute to the SolidJS documentation, the timing of your contribution can influence the approach we take. If it's before mid-October, it would be better to merge it into the current version of the document. However, if the contribution is expected after mid-October, we might need to consider adding a separate section for SolidJS.

**Comment by XiNiHa** [comment]
Personally, I'd want to merge the Solid integration (along with the docs? or docs as a follow-up? not sure 🤷‍♂️) after the V2 release of the core to minimize the efforts required while preparing for the V2 release. However, if the team expects my PR to be merged before V2, I'm also open to that 😅

**Comment by ho991217** [comment]
I'd appreciate it if you would merge after we launch docs v2 :)
