### ISSUE TITLE
[질문] push로 인해 stack에 쌓인 액티비티들을 한번에 없앨 수 있는 방법에 대한 문의입니다

### ISSUE THREAD

**Issue by uthem150** [daangn/stackflow#525]
안녕하세요,
이전에 pop을 할 때, 배열을 함께 지워야 하는지에 대해 pull request를 드렸던 학생입니다.

해당 부분 외에, 추가로 궁금한 사항이 있었는데, 
https://stackflow.so/ 문서에는 궁금한 부분에 대한 내용이 없어서
좋은 방법이 있는지에 대한 문의를 드리고자 issue를 남기게 되었습니다.

stackflow를 활용한 개발 도중, push를 통해 액티비티들을 추가하다 보면,
'홈 버튼' 기능과 같이, 쌓인 이전 액티비티들을 모두 초기화하고, 
처음으로 돌아가고자 하는 상황에 대한 처리도 필요하다는 생각을 하게 되었습니다.

액티비티들을 1개씩 push하고, pop하는 방법 외에,
clear하는 함수는 따로 문서에 제공되어있지 않아

아래와 같이, 배열 길이만큼 pop을 반복하는 식으로 기능을 대신하고 있는데,
혹시 별도의 제공되는 기능이나, 더 좋은 구현 방식이 있다면 알 수 있을까요?

```
	const activeActivities = stack.activities.filter(
		(activity) => activity.transitionState === 'enter-active' || activity.transitionState === 'enter-done'
	);

	for (let i = activeActivities .length; i > 1; --i) {
		pop({ animate: false });
	 }
```

**Comment by dohyun-ko** [comment]
안녕하세요, 같은 문제를 겪었고 `pop()`의 첫 파라미터로 정수값을 넣으면 한번에 여러 activity를 초기화하는 기능이 구현되어있음을 발견했습니다.
그러나 docs에 적혀있지 않아서 혼란이 발생한 듯 합니다.
`pop(3, { /* additional options */})와 같은 형식으로 사용하면 한 번에 3개의 activity를 pop할 수 있습니다!

#545 이 PR에서 문서 수정을 제안했습니다

**Comment by uthem150** [comment]
반복문만큼 pop을 실행시키는 작업을 추가로 적어도 되지 않는 방법이 있었군요!
답변해주셔서 감사합니다.

하지만, 현재 쌓여있는 만큼에 대해 한번에 pop을 주는 방법은 따로 없어서,
```
const activeActivities = stack.activities.filter(
	(activity) => activity.transitionState === 'enter-active' || activity.transitionState === 'enter-done'
);
```
위 방법과 같이, active상태의 Activities는 찾는 작업이 여전히 필요하긴 하겠군요.

저는 현재 간단히 window.location.reload()를 통해, 페이지를 새로고침 해서, 
쌓여있는 액티비티들을 초기화하는 방식을 우회해서 쓰고 있는데,

애니메이션 효과를 주면서, 쌓인 액티비티들을 쉽게 pop 하는 좋은 방법이 있으면 좋겠네요..!
