### ISSUE TITLE
Pull Request 템플릿 추가 건의

### ISSUE THREAD

**Issue by woochanleee** [daangn/stackflow#54]
PR 템플릿이 있으면 좋을 것 같다고 생각합니다.

**Comment by tonyfromundefined** [comment]
@woochanleee 템플릿에 어떤 내용이 들어가면 좋을까요?? ㅎㅎ

**Comment by woochanleee** [comment]
음..🤔  제가 PR를 할 당시 템플릿이 없어 어떤식으로 내용을 풀어가야할지 막막했어서 이 의견을 냈습니다!
그런데 템플릿에 어떤 내용을 넣을지 생각 해보니 PR의 종류가 **버그 수정** 으로 한정 되는게 아니더라구요.

그래서 다음과 같은 내용으로 구성되면 어떨까 생각해보았습니다! 확인후 피드백 주세요 ㅎㅎ~~어렵네요😓~~

# 제목

## PR 종류

- [ ] 버그 수정
- [ ] 기능 추가
- [ ] 문서 수정


## 문제점

## 해결방안

## 스크린샷(선택)

### Before(선택)

### After(선택)

## 관련된 이슈(선택)


## 기능 설명

## 관련된 이슈(선택)



## 문제가 되는 부분(선택)

## 수정한 부분에 대한 설명

## 관련된 이슈(선택)

**Comment by tonyfromundefined** [comment]
시간이 오래 지나서 Close 하겠습니다
