### ISSUE TITLE
CONTRIBUTING.md 내용 추가 제안

### ISSUE THREAD

**Issue by woochanleee** [daangn/stackflow#58]
# 경험
메인테이너 분들은 어떤 IDE를 쓰실진 모르겠지만, 저 같은 경우엔 vscode를 사용합니다.
기여하기 위해 karrotframe을 클론 받고 프로젝트를 열면 아래 사진과 같이 IDE가 패키지 인식을 못합니다.
![image](https://user-images.githubusercontent.com/48552260/114882536-03dee680-9e3f-11eb-8500-290fdf865a0a.png)
근데 신기한점은 `yarn && cd packages/karrotframe && yarn build:dts && yarn build:runtime --watch` 명령어를 실행시 문제 없이 작동합니다.

그래서 저는 의아한 채로 IDE의 제 기능을 활용하지 못 한채 코드를 수정하며 기여를 하였습니다.

## 해결 방법
IDE가 패키지를 인식하도록 하는 방법은 매우 간단하였는데요.

### 1번 방법
[settings.json](https://github.com/daangn/karrotframe/blob/master/.vscode/settings.json#L7)에 잘 설정 되어 있어, vscode로 프로젝트를 첫 오픈 시 우측 하단에 아래와 같은 문구와 함께 TypeScript 버전을 교체하겠냐는 팝업이 뜹니다.~~저는 이런거 함부로 안 누르는 성격이라..~~
![image](https://user-images.githubusercontent.com/48552260/114883105-9089a480-9e3f-11eb-96e6-75dd2999bba5.png)

allow를 클릭 후 vscode를 껐다 키면 아래와 같이 IDE가 인식을 하게 됩니다.
![image](https://user-images.githubusercontent.com/48552260/114883820-376e4080-9e40-11eb-8e85-605c6577d430.png)

### 2번 방법

vscode를 켜논 상태에서, `⌘ + ⇧ + P`를 하면 아래와 같은 상태가 됩니다.
![image](https://user-images.githubusercontent.com/48552260/114886322-6685b180-9e42-11eb-8465-c36225c8d644.png)

해당 입력창에 아래와 같이 채워주고 엔터를 누르면,
`>TypeScript: Select TypeScript Version...`

아래 사진과 같은 선택 창이 나오는데 **Use Workspace Version 4.1.5-pnpify** 부분을 클릭후 vscode를 재시작 합니다.
![image](https://user-images.githubusercontent.com/48552260/114886498-8917ca80-9e42-11eb-871f-357cb761b8a5.png)

## 결론
제가 yarn2, workspace, pnp 등에 대한 지식이 없다보니 이런 실수를 범했네요.
혹시라도 저와 같이 IDE가 인식을 못해 당황해 할 수 있는 분들을 위해 `CONTRIBUTING.md`에 위 해결 방법에 대한 내용을 추가하는게 좋지 않을까? 라는 생각을 해보았습니다.

의견 부탁드립니다!

**Comment by tonyfromundefined** [comment]
좋은거 같아요! PR 추가해서 리뷰어 등록해드릴게요~ ㅎㅎ

**Comment by tonyfromundefined** [comment]
pnp 인터페이스를 안쓰게 되었어요. (`nodeLinker: node-modules`) 해당 Issue는 Close 할게요.
