### ISSUE TITLE
[Navigator] replace without animate option doesn't work after using history.push 

### ISSUE THREAD

**Issue by beautifulife** [daangn/stackflow#85]
navigator.replace without animate option doesn't work after using history.push 

In my opinion, when using history.push, _si is missing. 
And, Because navigator.replace with animation doesn't set _si, karrotframe route also doesn't work

[ex flow] 
page load -> history.push('/same-path?with-query-string') -> navigator.replace(/some-other-path) -> the page is not changed

**Comment by tonyfromundefined** [comment]
기존 Karrotframe 이슈이고, 시간이 꽤 오래 지나서, Close 할게요!
