### ISSUE TITLE
기능 건의해요!

### ISSUE THREAD

**Issue by lorraine98** [daangn/stackflow#95]
### 현황
- si로 1일 땐 x버튼이 나오고, 1 이상일 땐 화살표 버튼이 나오면서 si가 낮은 숫자로 이동해요.

### 배경
- 한 페이지 컴포넌트 내에서 `step`이란 상태로 페이지를 그리고 싶어요.
- 덧붙이자면, 초기 상태를 `step 1`으로 만들고 `step 2`로 넘어가는 버튼을 클릭하면 하나의 페이지 이지만 `step 2`에 맞는 페이지를 그리고 싶어요.
- 그리고 `step 2`에서 뒤로가기 버튼을 눌렀을 때 `step 1`으로 보내고 싶어요.
- 즉, `step 1`일 땐 `x` 표시가, `step 2`일 땐 step 1으로 가는 `화살표`가 떴으면 좋겠어요.
(지금은 한 페이지이기 때문에 step과 상관없이 뒤로가기가 돼요)
- 자세히 말하면, useState를 사용하여 step 2로 가는 버튼을 누를 때 setStep으로  step 이란 상태를 2로 만들어줄 수 있지만
- 뒤로가기를 누를 땐 setStep을 해줄 수가 없어요.

### 건의
- 뒤로가기 버튼에 기능을 넣을 수 있으면 좋겠어요.
- 예를 들어 `setStep을 넣어 step을 1로 변형 시킬 수 있다` 같이요!
- 아니면 한 페이지 내에서 또 다른 si가 있어 전체 흐름과 별개로 해당 페이지에서 캐롯프레임을 사용하고 싶어요!

**Comment by tonyfromundefined** [comment]
직접 history로 구현하면 돼요. 백버튼은 appendLeft를 통해 직접 같은 모양으로 주입하면 되구요. 시간이 꽤 오래 지나서 Close할게요!
